name: Build Docker Image
on: workflow_call

jobs:
  build-image:
    runs-on: ubuntu-22.04
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    container:
      image: lucasalt/act_base:latest # Use to get the docker-compose command
    steps:
      - uses: act10ns/slack@v2
        with:
          status: starting
          message: Pull request has problems in initialising containers.
          config: .github/workflows/config/slack.yml
        if: failure()
      - uses: actions/checkout@v3 # Use to copy the files from current directory
      - name: Complexity
        run: |
          echo "action_step='Code Complexity'" >> $GITHUB_ENV
          docker-compose -f scripts/docker_lintage/docker-compose.yaml run complexity
      - name: Documentation
        run: |
          echo "action_step='Code Documentation'" >> $GITHUB_ENV
          docker-compose -f scripts/docker_lintage/docker-compose.yaml run documentation
      - name: Test Coverage
        run: |
          echo "action_step='Test Coverage'" >> $GITHUB_ENV
          docker-compose -f scripts/docker_lintage/docker-compose.yaml run coverage
      - uses: act10ns/slack@v2
        with:
          status: ${{job.status}}
          message: Shame on ${{ github.event.pull_request.user.login }}! Your Code is not compliant with ${{ env.action_step }}.
          #channel: '#general'
          config: .github/workflows/config/slack.yml
        if: failure()
      - name: Unit Test
        run: |
          docker-compose -f scripts/docker_lintage/docker-compose.yaml run unittest
      - uses: act10ns/slack@v2
        with:
          status: ${{job.status}}
          steps: ${{toJson(steps)}}
          config: .github/workflows/config/slack.yml
        if: always()
