name: Lintage, tests
on:
  push:
jobs:
  lintage:
    runs-on: ubuntu-22.04
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    container:
      image: lucasalt/act_base:latest # Use to get the docker-compose command
    steps:
      - uses: act10ns/slack@v1
        with:
          status: starting
          message: Pull request
        if: always()
      - uses: actions/checkout@v3 # Use to copy the files from current directory
      - name: Test static
        run: |
          set -euxo
          docker-compose -f script/docker_lintage/docker-compose.yaml up --build format_test
      - name : Complexity
        run: |
          docker-compose -f script/docker_lintage/docker-compose.yaml up --build complexity
      - name : Documentation
        run: |
          docker-compose -f script/docker_lintage/docker-compose.yaml up --build documentation
      - name : Unit
        run: |
          docker-compose -f script/docker_lintage/docker-compose.yaml up --build unit
      - uses: act10ns/slack@v1
        with:
          status: ${{job.status}}
          steps: ${{toJson(steps)}}
        if: always()
