name: complete build
on: [pull_request, workflow_call]
jobs:
  lintage-checks:
    runs-on: ubuntu-22.04
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    container:
      image: lucasalt/act_base:latest # Use to get the docker-compose command
    steps:
      - uses: act10ns/slack@v2
        with:
          status: starting
          message: Pull request opened successfully by ${{ github.event.pull_request.user.login }}
        if: always()
      - uses: actions/checkout@v3 # Use to copy the files from current directory
      - name: Test formatting
        run: |
          set -euxo
          docker-compose -f scripts/docker_lintage/docker-compose.yaml up --build format_test
      - name: Complexity
        run: |
          docker-compose -f scripts/docker_lintage/docker-compose.yaml up --build complexity
      - name: Documentation
        run: |
          docker-compose -f scripts/docker_lintage/docker-compose.yaml up --build documentation
      - name: Test Coverage
        run: |
          docker-compose -f scripts/docker_lintage/docker-compose.yaml up --build coverage
        uses: act10ns/slack@v2
          with:
            status: starting
            message: Shame on ${{ github.event.name.pull_request.user.login }}! Test coverage is not enough.
          if: failure()
      - name: Unit Test
        run: |
          docker-compose -f scripts/docker_lintage/docker-compose.yaml up --build unittest
      - uses: act10ns/slack@v2
        with:
          status: ${{job.status}}
          steps: ${{toJson(steps)}}
        if: always()
