name: Build Docker Image
on: [pull_request, workflow_call]
jobs:
  build-image:
    runs-on: ubuntu-22.04
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    container:
      image: lucasalt/act_base:latest # Use to get the docker-compose command
    steps:
      - uses: act10ns/slack@v2
        with:
          status: starting
          message: Pull request opened successfully by ${{ github.event.pull_request.user.login }}
        if: always()
      - uses: actions/checkout@v3 # Use to copy the files from current directory
      - name: Test formatting
        run: |
          echo "STEP=$(echo Test Formatting | cut -c 1-20)" >> $STEP
          set -euxo
          docker-compose -f scripts/docker_lintage/docker-compose.yaml run format_test
      - name: Complexity
        run: |
          echo "STEP=$(echo Code Complexity | cut -c 1-20)" >> $STEP
          docker-compose -f scripts/docker_lintage/docker-compose.yaml run complexity
      - name: Documentation
        run: |
          echo "STEP=$(echo Documentation | cut -c 1-20)" >> $STEP
          docker-compose -f scripts/docker_lintage/docker-compose.yaml run documentation
      - name: Test Coverage
        run: |
          echo "STEP=$(echo Test Coverage | cut -c 1-20)" >> $STEP
          docker-compose -f scripts/docker_lintage/docker-compose.yaml run coverage
      - uses: act10ns/slack@v2
        with:
          status: ${{job.status}}
          message: Shame on ${{ github.event.pull_request.user.login }}! Your Code is not compliant with ${{ STEP }}.
          #channel: '#general'
        if: failure()
      - name: Unit Test
        run: |
          docker-compose -f scripts/docker_lintage/docker-compose.yaml run unittest
      - uses: act10ns/slack@v2
        with:
          status: ${{job.status}}
          steps: ${{toJson(steps)}}
        if: always()
