name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container:
      image: lucasalt/act_base:latest # Use to get the docker-compose command
    steps:
      - uses: actions/checkout@v3 # Use to copy the files from current directory
      - name: install pip and dependencies
        run: |
          pip install --upgrade pip --no-cache
          pip install -U --no-cache-dir -r requirements.txt
      - name: Test formatting
        run: |
          set -euxo
          make test_static_all
      - name: Complexity
        run: |
          make complexity
      - name: Documentation
        run: |
          make documentation
      - name: Test Coverage
        run: |
          make coverage
      - name: Run Tests
        run: |
          make unittest
